name: CI/CD for Java App (Minikube Local)

	on:
	  push:
	    branches: [ main ]
	  pull_request:
	    branches: [ main ]

	jobs:
	  build-deploy:
	    runs-on: ubuntu-latest

	    steps:
	    - name: Checkout code
	      uses: actions/checkout@v4

	    - name: Set up JDK 21
	      uses: actions/setup-java@v4
	      with:
	        distribution: 'temurin'
	        java-version: '21'
	    - name: Build with Gradle
	      run: ./gradlew build
	    - name: Start Minikube
	      run: |
	        minikube start --driver=docker --memory=1800mb
	    - name: Point Docker to Minikube
	      run: |
	        eval $(minikube docker-env)

	    - name: Build Docker image in Minikube
	      run: |
	        docker build -t devops-java-app .

	    - name: Deploy to Kubernetes
	      run: |
	        kubectl apply -f k8s/deployment.yaml
	        kubectl apply -f k8s/service.yaml

	    - name: Check pods
	      run: |
	        kubectl get pods